### ISSUE TITLE
[sound_eval] Higher values from leq_interval than from leq_period ?

### ISSUE THREAD

**Issue by jfbus** [sfera-labs/exo-sense-pi-kernel-module#10]
Most of the time, I get values from leq_interval higher that the values I get from leq_period in the same period.

I understood that leq_interval was the RMS of all leq_period values, meaning that leq_interval should never be higher than all values from leq_period.

Is there a bug or did I miss something ?

My test setup is:
```
echo 2 > /sys/class/exosensepi/sound_eval/interval_sec
echo S > /sys/class/exosensepi/sound_eval/weight_time
echo A > /sys/class/exosensepi/sound_eval/weight_freq
```
(My real life values are 60 / F / A, but 2 / S / A is easier to reproduce)

```
ls /sys/class/exosensepi/sound_eval/leq* ; while :; do echo "---"; cat /sys/class/exosensepi/sound_eval/leq*; sleep 1; done

/sys/class/exosensepi/sound_eval/leq_interval  /sys/class/exosensepi/sound_eval/leq_period
---
58507 1626702002686
57020 1626702002686
---
58507 1626702002686
55623 1626702003686
---
58568 1626702004686 => higher than the previous 2 values and the current value
55492 1626702004686
---
58568 1626702004686
52481 1626702005686
---
61007 1626702006686 => higher than the previous 4 values and the current value
60350 1626702006686
---
61007 1626702006686
56180 1626702007686
---
67154 1626702008686 => higher than all the previous values
66792 1626702008686
---
67154 1626702008686
61982 1626702009686
```

**Comment by bancha321** [comment]
There was an error in the README file, 'S' is not a correct value for slow time weighting, while 's' is a valid value.
I just fixed the README file replacing the wrong uppercase letters with the lowercase correct ones.
In your previous case you tried to set the time weighting to slow, but the new parameter wasn't accepted as valid so the fast time weighting stayed in use.
If you change your terminal commands with
`echo s > /sys/class/exosensepi/sound_eval/weight_time`
`echo a > /sys/class/exosensepi/sound_eval/weight_freq`
`echo 1 > /sys/class/exosensepi/sound_eval/interval_sec`
you'll get the same period result (1sec) as the interval result (1sec)

**Comment by bancha321** [comment]
P.S. I'll make the change to accept also the parameter in uppercase, and a feedback of error in case of invalid value. In the meantime I ask you kindly to use the utility just with lower cases, until the next software update

**Comment by jfbus** [comment]
I just switched to lowercase. Thanks for your help
